package com.students.spacegame.supabase

import io.github.jan.supabase.createSupabaseClient
import io.github.jan.supabase.postgrest.Postgrest
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class SupabaseClient @Inject constructor() {
    val client = createSupabaseClient(
        supabaseUrl = "Вставить ссылку на Supabase",
        supabaseKey = "Вставить ключ Supabase"
    ) {
        install(Postgrest)
    }
}


/*
* -- Таблица для хранения результатов игр
create table game_scores (
    id bigint generated by default as identity primary key,
    player_name text not null,
    score integer not null,
    level integer not null,
    date bigint not null default (extract(epoch from now()) * 1000)
);

-- Таблица для хранения уровней сложности (DifficultyLevel)
create table difficulty_levels (
    name text primary key,
    enemy_speed_multiplier real not null,
    enemy_health_multiplier real not null
);

-- Заполнение таблицы уровней сложности начальными значениями
insert into difficulty_levels (name, enemy_speed_multiplier, enemy_health_multiplier) values
    ('EASY', 0.7, 0.8),
    ('NORMAL', 1.0, 1.0),
    ('HARD', 1.3, 1.5),
    ('NIGHTMARE', 1.6, 2.0);

-- Индекс для быстрого поиска топ-результатов
create index idx_game_scores_score_desc on game_scores (score desc);

-- Индекс для поиска по имени игрока
create index idx_game_scores_player_name on game_scores (player_name);

* */